name: Any Branch CI/CD with Approval

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build
        run: echo "build"

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Test
        run: echo "test"
        
  db-migration-staging:
    runs-on: ubuntu-latest
    needs: test
    environment: staging
    steps:
      - name: Run DB Migration
        run: echo "Run DB Migration to staging"
        
  deploy-staging:
    runs-on: ubuntu-latest
    needs: db-migration-staging
    environment: staging
    steps:
      - name: Deploy to staging
        run: echo "deploy to staging"

  post-deploy-test-staging:
    runs-on: ubuntu-latest
    needs: deploy-staging
    environment: staging
    steps:
      - name: Integration tests for staging
        run: echo "Integration tests for staging"        

  deploy-production:
    runs-on: ubuntu-latest
    needs: post-deploy-test-staging
    environment: production   # 👈 approval gate here
    steps:
      - name: Deploy to production
        run: echo "deploy to production"
